[build-system]
requires = [
  "setuptools>=61.2",
  "setuptools_scm[toml]>=6.2",
  "oldest-supported-numpy",
  "Cython"
]

build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
markers = [
  "slow: mark a test as slow.",
  "highmem: mark a test as taking high memory."
]
