#======================================================================================================================#
#                                       Cluster Generator Configuration File                                           #
#                                     +--------------------------------------+                                         #
#                                                                                                                      #
# This file contains the basic configuration settings for cluster_generator. See the line comments for details on      #
#   specific settings. Users are encouraged to edit settings and / or change settings as necessary.                    #
#                                                                                                                      #
# --- These settings are accessed using the cg.cgparams variable ------------------------------------------------------#
#======================================================================================================================#
system:
  # -- These are system wide settings for basic usage of the cluster_generator software -- #
  logging:
    # -- Settings regarding message logging -- #
    ufstring: "%(name)-3s : [%(levelname)-9s] %(asctime)s %(message)s" # Logger's string format for output
    level: "INFO" # The logging level to display

    developer_log:
      # -- These settings can be used to control the output of the development logger (no output to terminal) -- #
      is_enabled: false
      output_directory: ~
      level: "DEBUG"
      format:  "%(name)-3s : [%(levelname)-9s] %(asctime)s %(message)s"
  text:
    spinners: true

  io:
    # -- Settings regarding io methodology -- #
#======================================================================================================================#
physics:
  # -- The physics settings are basic user-configurable physical parameters -- #
  hydrogen_abundance: 0.76 # The primordial hydrogen abundance (0.76 generally accepted value)

#======================================================================================================================#
gravity:
  # -- These settings are all regarding the gravity systems in cluster generator -- #
  general:
    # -- General gravity settings for types / classes of gravity -- #
    mond:
      # -- MOND specific settings -- #
      a0: !unyt # The acceleration threshold constant for MOND. typically 1.2e-10 m/s^2
        input_scalar: 1.2e-10
        units: "m/s**2"
  QUMOND:
    # - Settings for the QUMOND implementation - #
    interpolation_function: !lambda "lambda x: ((1 / 2) * (np.sqrt(1 + (4 / x)) + 1))"
  AQUAL:
    # - Settings for the AQUAL implementation - #
    interpolation_function: !lambda "lambda x: x/(1+x)"
  EMOND:
    # - Settings for the EMOND implementation - #
    a0_function: !lambda "lambda x,a=0.003868,A=0.30944,p0=-7.614: a + (A-a)*(0.5*np.tanh(np.log10(x/p0)**2) + 0.5)"

#======================================================================================================================#
numerical:
  # -- These are settings regarding the numerical methods implemented in the code -- #
  implicit:
    # -- These are settings for implicit function solutions in alternative gravity theories -- #
    check_tolerance: !!float 1e-10 # The tolerance below which we skip optimization because the guess is sufficiently good.
    solve_tolerance: !!float 1e-7 # The tolerance required once the code actually reaches the implicit solver.

#======================================================================================================================#
plotting:
  # These are options for any of the default plots generated in cluster generator.
  defaults:
    # -- Latex settings -- #
    text.usetex: false
    # -- Tick Settings -- #
    xtick.major.size: 8
    ytick.major.size: 8
    xtick.minor.size: 5
    ytick.minor.size: 5
    xtick.direction: "in"
    ytick.direction: "in"