# .github/workflows/generate_answers.yml

name: Generate and Upload Test Answers

on:
  workflow_dispatch:
    inputs:
  schedule:
    - cron: '0 0 */60 * *'
  create:
  release:
    types: [published]

jobs:
  generate-answers:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.8', '3.9', '3.10']

    steps:
    # Step 1: Set up the specific version of Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    # Step 2: Check out the repository to the runner
    - name: Check out repository
      uses: actions/checkout@v2

    # Step 3: Install build tools for both Ubuntu and macOS
    - name: Install build tools on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential

    - name: Install build tools on macOS
      if: matrix.os == 'macos-latest'
      run: |
        brew update
        brew install gcc

    # Step 4: Install required Python dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 5: Install cluster_generator
    - name: Install the library
      run: |
        pip install cython
        pip install .

    # Step 6: Run tests to generate answers and package them
    - name: Run tests to generate answers
      run: |
        mkdir -p ./answers
        ls ./cluster_generator
        pytest "./cluster_generator" --answer_dir='../answers' --answer_store --package
      env:
        PYTHON_VERSION: ${{ matrix.python-version }}
        OS_NAME: ${{ matrix.os }}
        CG_VERSION: $(python -c "import importlib.metadata; print(importlib.metadata.version('cluster_generator'))")

    # Step 7: Upload the generated test answers as artifacts
    - name: Upload test answers as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: answers-${{ github.ref_name }}-${{ matrix.python-version }}-${{ matrix.os }}-${{ env.CG_VERSION }}
        path: ./answers/cg_answers_*.tar.gz
        retention-days: 60
