name: Tests

on:
  push:
  workflow_dispatch:
    inputs:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.8" ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip' # caching pip dependencies
      - name: Install dependencies
        run: |
          sudo apt-get install build-essential  python3-dev
          python3 -m pip install --upgrade pip
          pip3 install pylint
          pip3 install pytest pytest-cov pytest-subtests
          pip3 install coveralls
          pip3 install -r requirements.txt
      - name: Setup
        run: |
          pip install -e .
      - name: Running pytest
        run: |
          pytest cluster_generator --doctest-modules --answer_dir="./tmp" --answer_store
          pytest cluster_generator --doctest-modules --cov=cluster_generator --cov-report=xml --answer_dir="./tmp"
          COVERALLS_REPO_TOKEN=tQ0ra8kUn56CDx6Cjp7Wil8Pp5qA9vTdK coveralls
